In [2]:
import os
all_datas=os.listdir()

In [3]:
import pandas as pd

In [4]:
all_merged=[]
for item in all_datas:
    if item.endswith(".csv"):
        df=pd.read_csv(item)
        all_merged.append(df)
print("loaded all the data sucessfully ")

loaded all the data sucessfully

In [5]:
len(all_merged)

367

In [7]:
all_merged[1]

,transaction,symbol,buyer,seller,quantity,rate,amount,date
0,2024010201058065,PHCL,20,58,10.0,302.0,3020.0,2024-01-02
1,2024010204013584,SHL,70,62,100.0,441.6,44160.0,2024-01-02
2,2024010205005211,NRN,71,42,10.0,470.0,4700.0,2024-01-02
3,2024010204013583,GHL,29,45,10.0,149.8,1498.0,2024-01-02
4,2024010201058064,DLBS,38,74,13.0,895.0,11635.0,2024-01-02
...,...,...,...,...,...,...,...,...
85430,2024010203000003,GBBL,57,36,100.0,375.0,37500.0,2024-01-02
85431,2024010203000002,GBBL,57,36,20.0,375.0,7500.0,2024-01-02
85432,2024010204000002,UMHL,14,57,10.0,212.1,2121.0,2024-01-02
85433,2024010204000001,AKPL,14,55,10.0,177.4,1774.0,2024-01-02
85434,2024010203000001,DDBL,42,85,200.0,784.6,156920.0,2024-01-02

In [8]:
final_datasets=pd.concat(all_merged,ignore_index=False)
final_datasets

,transaction,symbol,buyer,seller,quantity,rate,amount,date
0,2024010103010653,GBBL,22,53,50.0,410.0,20500.0,2024-01-01
1,2024010105005330,NIBLPF,26,10,5647.0,9.3,52517.1,2024-01-01
2,2024010104015466,PRIN,20,34,10.0,851.0,8510.0,2024-01-01
3,2024010101071456,GVL,3,34,200.0,418.5,83700.0,2024-01-01
4,2024010103010652,HLI,39,34,10.0,438.0,4380.0,2024-01-01
...,...,...,...,...,...,...,...,...
45111,2025082601000001,HBL,34,49,200.0,214.0,42800.0,2025-08-26
45112,2025082605000001,NTC,75,57,11.0,866.6,9532.6,2025-08-26
45113,2025082604000002,NHPC,36,55,10.0,211.0,2110.0,2025-08-26
45114,2025082604000001,NHPC,34,55,10.0,211.0,2110.0,2025-08-26
45115,2025082603000001,CBBL,44,84,20.0,1093.4,21868.0,2025-08-26

In [9]:
final_datasets.shape[0]

32793448

In [10]:
final_datasets.shape[0]/1000000

32.793448

In [11]:
final_datasets.to_csv("merged_datasets.csv",index=False)